# Generated by Django 3.2.6 on 2022-01-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Загрузка CPU', models.FloatField()),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
        ),
    ]
