# Generated by Django 3.2.6 on 2022-01-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='Загрузка CPU',
            field=models.FloatField(null=True),
        ),
    ]
