# Generated by Django 3.2.6 on 2022-01-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_alter_cpu_загрузка cpu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='Загрузка CPU',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
    ]
