# Generated by Django 3.2.6 on 2022-01-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_auto_20220117_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='Загрузка CPU',
            field=models.DecimalField(decimal_places=4, max_digits=4),
        ),
    ]
